name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
      GPR_USER: ${{ github.actor }}
      GPR_KEY: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5.6.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup GPG key
        run: |
          if [ -n "${{ secrets.GPG_PRIVATE_KEY }}" ]; then
            echo "Importing existing GPG key from secrets..."
            echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          else
            echo "Generating automated GPG key for signing..."
            gpg --batch --passphrase '' --quick-generate-key "Rhdevs71 <drahmanhakim71@gmail.com>" default default never
          fi
          KEY_ID=$(gpg --list-secret-keys --keyid-format=long | awk '/sec/{split($2,a,"/"); print a[2]; exit}')
          git config --global user.signingkey "$KEY_ID"
          git config --global commit.gpgsign true
          git config --global tag.gpgsign false
          git config --global user.name "Rhdevs71"
          git config --global user.email "drahmanhakim71@gmail.com"
          echo "GPG key setup completed with Key ID: $KEY_ID"

      - name: Release
        uses: cycjimmy/semantic-release-action@v5
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest
        if: steps.release.outputs.new_release_published == 'true'
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: 'Piko Patches ${{ steps.release.outputs.new_release_git_tag }}'
          subject-path: patches/build/libs/patches-*.mpp